version: '2'

networks:
  front-tier:
  back-tier:

services:
  prometheus:
    image: prom/prometheus:v2.36.2
    container_name: prometheus
    user: root
    volumes:
      - ./prometheus/:/etc/prometheus/
      - /home/$USER/share/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
#      - pushgateway:pushgateway
   # depends_on:
     # - 
    networks:
      - back-tier
    restart: always
  node-exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9101:9101
    networks:
      - back-tier
    restart: always
    deploy:
      mode: global
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - /home/$USER/share/kibana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini 
    env_file:
      - ./grafana/config.monitoring
    networks:
      - back-tier
      - front-tier
    restart: always

