version: "3.7"
services:
  gateway:
    image: nginx
    network_mode: "host"
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
     # - ./run_env/log/:/var/log/nginx/
      - /var/log/nginx/:/var/log/nginx/
      - ./sites-enabled/default:/etc/nginx/sites-enabled/default
    command:
      - bash
      - -c
      - 'nginx -g"daemon off;"'
    ports:
      - 5040:5040
   # extra_hosts:
     # - "host.docker.internal:host-gateway"
