name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SERVER: ${{ secrets.SERVER }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1


    - name: Download data
      run:
        make download_data_ci SERVER=$SERVER

    - name: ci_training_pipeline
      run: make training_ci

    
    - name: Run predictor_up
      run: make predictor_up SERVER=$SERVER

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1

    - name: Run predictor_curl
      # Use the retry action
      uses: nick-fields/retry@v2
      with:
        max_attempts: 10
        retry_on: error
        timeout_seconds: 60
        # You can specify the shell commands you want to retry here
        command: |
          docker logs -f model1-model_predictor-1
          docker logs -f model2-model_predictor-1
          make predictor_curl		

    # - name: Run predictor_curl
    #   run: make predictor_curl

    # - name: Run predictor_down
    #   run: make predictor_down
