name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SERVER: ${{ secrets.SERVER }}

    steps:
    - uses: actions/checkout@v3

    - name: Run download_data
      run: python3 src/minio/folder_getter.py --minio_server $SERVER --dst_path data
    
    - name: Run predictor_up
      run: make predictor_up SERVER=$SERVER

    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1

    - name: Run predictor_curl
      run: make predictor_curl

    # - name: Run predictor_down
    #   run: make predictor_down
