name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Run predictor_up
      env:
        MLFLOW_URI: ${{ secrets.MLFLOW_URI }}
      run: make predictor_up MLFLOW_URI=$MLFLOW_URI

    - name: Setup upterm session
      uses: lhotari/action-upterm@v1

    - name: Run predictor_curl
      run: make predictor_curl

    - name: Run predictor_down
      run: make predictor_down
