name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SERVER: ${{ secrets.SERVER }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip' # caching pip dependencies
    - run: pip install -r requirements.txt

    - name: Download data
      run:
        make download_data_ci SERVER=$SERVER
    
    - name: Run predictor_up
      run: make predictor_up SERVER=$SERVER

    # - run: |
    #     echo "Waiting for predictor up"
    #     sleep 30
    #     echo "Predictor up success!!!"

    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1

    - name: Run predictor_curl
      run: timeout 60 make predictor_curl || code=$?; if [[ $code -ne 124 && $code -ne 0 ]]; then exit $code; fi

    # - name: Run predictor_down
    #   run: make predictor_down
