name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SERVER: ${{ secrets.SERVER }}

    steps:
    - uses: actions/checkout@v3

    - name: Prepare
      run: |
        pip install -r requirements.txt
        make download_data_ci SERVER=$SERVER
    
    - name: Run predictor_up
      run: make predictor_up SERVER=$SERVER

    # - name: Setup upterm session
    #   uses: lhotari/action-upterm@v1

    - name: Run predictor_curl
      run: make predictor_curl

    # - name: Run predictor_down
    #   run: make predictor_down
